### PR TITLE
Set up multiple typescript projects

### PR DESCRIPTION
**Pull request by psrpinto**
(Not opened yet upstream as it depends on https://github.com/vector-im/hydrogen-web/pull/1056 so must wait for that one to be merged first)

Requires #11

----

In the current typescript setup, attempting to use the `WebWorker` typescript library will not work, as that library is not part of typescript's default libraries. Attempting to require the library through triple-slash directives will result in an error:

```typescript
// sync-worker.ts

/// <reference lib="WebWorker" />
```

```shell
Definitions of the following identifiers conflict with those in another file:
ImportExportKind, TableKind, ValueType ...
```

This happens because the `WebWorker` and `DOM` (which is part of the default libraries) libs define some of the same types. I consulted with a colleague who has experience with Web Workers in typescript and they recommended using typescript's [project references](https://www.typescriptlang.org/docs/handbook/project-references.html) feature to address this issue.

This PR "splits" the codebase into three typescript projects, which share common configuration, but can also have their own configuration to, e.g. import libraries. These projects are:

1. `app`: Contains all code except workers. Requires the `DOM` and `DOM.iterable` libs
2. `workers`: Contains workers only. Requires the `WebWorkers` lib. References the `app` project.
3. `sdk`: Contains all code except workers. Requires the `DOM` and `DOM.iterable` libs. Only emits declarations.

The top-level `tsconfig.json` only contains references to each project.

### Caveats

1. When using project references, the `tsc` CLI command **requires** the `--build` flag. Not passing the `--build` flag will result in success, but no code has been checked/compiled.
2. Project references **require** code to be emitted, even if you just want to lint. Compiled files are placed in a `.typescript` directory.

### CODE REVIEW

**Review by ashfame — APPROVED** [review]
No comments from my side as I don't know TypeScript. Sail away ⛵

**Comment by psrpinto** [comment]
I rebased this on top of `integration-sync-worker`, thus the force-push, didn't change any code.

**Comment by ashfame** [comment]
@psrpinto You shouldn't need to rebase your "sync in worker" PRs on `integration-sync-worker` for creating PRs unless you had a specific reason for doing that.

**Comment by psrpinto** [comment]
Indeed there was no need to do so, and I won't do it with future PRs. It's just that this branch was created before the `integration-sync-worker` existed and I wanted to make sure it was based on that branch. In practice nothing changed, except for the commit hashes.

**Comment by psrpinto** [comment]
This PR was reverted (by force-push) on `integration-sync-worker`, since it turns out this approach does not fix the issues with workers in typescript we were trying to address.

**Pull request merged**
